title: "Exploring U.S. Federal Holidays"
description: A simple Jekyll website with minimal configuration
theme: minima
markdown: kramdown
sass:
  style: compressed
  load_paths:
    - assets/css
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
baseurl: "/assignment-4-packages-and-shiny-apps-xiaoranzhong0924"
